#!/usr/bin/python

import sys
import math

class IQ205:

	def display_help(self):
		print("USAGE")
		print("\t./205IQ u q [IQ1] [IQ2]\n")
		print("DESCRIPTION")
		print("\tu    predetermined mean (100)")
		print("\tq    predetermined standard deviation")
		print("\tIQ1  minimum IQ")
		print("\tIQ1  maximum IQ")

	def check_error(self):
		if len(sys.argv) < 3 or len(sys.argv) > 5:
			self.display_help()
			exit(84)
		if sys.argv[1] == "-h" or sys.argv[1] == "--help":
			self.display_help()
			exit(0)
		try:
			self.u = int(sys.argv[1])
			if self.u > 200 or self.u < 0:
				self.display_help()
				exit(84)
			self.q = int(sys.argv[2])
			if len(sys.argv) == 4:
				self.miniIQ = int(sys.argv[3])
			if len(sys.argv) == 5:
				self.miniIQ = int(sys.argv[3])
				self.maxiIQ = int(sys.argv[4])
		except:
			print("Error: invalid argument")
			exit(84)

	def calculate_density(self, x):
		res1 = 1 / (self.q * math.sqrt(2 * math.pi))
		res2 = math.exp(-(math.pow(x - self.u, 2)) / (2 * pow(self.q, 2)))
		result = float(res1) * float(res2)
		return result
	
	def populationIQ(self):
		totalProb = 0.0
		count = 0
		while count < 201:
			result = self.calculate_density(count) * 100
			totalProb = totalProb + float(result);
			print(str(count) + " " + str(format(result, ".2f")))
			count = count + 1
		
	def calcMin(self):
		totalProb = 0.0
		count = 0.0
		while count <= self.miniIQ:
			result = self.calculate_density(count)
			totalProb = totalProb + float(result);
			count = count + 0.01
		print(str(format(totalProb, ".1f")) + "% of people have an IQ inferior to " + str(self.miniIQ))

	def calcBetween(self):
		totalProb = 0.0
		count = 0.0
		while count < 200:
			result = self.calculate_density(count)
			if (count >= self.miniIQ and count < self.maxiIQ):
				totalProb = totalProb + result;
			count = count + 0.01
		print(str(format(totalProb, ".1f")) + "% of people have an IQ between " + str(self.miniIQ) + " and " + str(self.maxiIQ))

		
if __name__ == '__main__':
	iq = IQ205()
	iq.check_error()
	if len(sys.argv) == 3:
		iq.populationIQ()
	elif len(sys.argv) == 4:
		iq.calcMin();
	else:
		iq.calcBetween();


			  
